#include <pic.h>
#include "lcd.h"
#include "homem.h"
#include "hardware.h"

void homem_inicio(void) {
    int a, b, c;

    a = 0;
    b = a + 1;
    c = a + 2;

    lcd_string((char *) "----------------", LCD_LINHA3);

    lcd_novo_char(0, stepA1);
    lcd_novo_char(1, stepA2);
    lcd_novo_char(2, stepA3);
    lcd_novo_char(3, stepA4);
    lcd_novo_char(4, stepA5);
    lcd_novo_char(5, stepA6);

    lcd_cursor_ddram(a, 1);
    lcd_putch(0);
    lcd_cursor_ddram(a, 0);
    lcd_putch(1);
    lcd_cursor_ddram(b, 1);
    lcd_putch(2);
    lcd_cursor_ddram(b, 0);
    lcd_putch(3);
    lcd_cursor_ddram(c, 1);
    lcd_putch(4);
    lcd_cursor_ddram(c, 0);
    lcd_putch(5);
}

void homem_corre_esquerda(void) {
    unsigned char a, b, c, d, e, f, g;

    for (a = 0; a < 11; a += 4) {
        b = a + 1;
        c = a + 2;
        d = a + 3;
        e = a + 4;
        f = a + 5;
        g = a + 6;

        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepB1);
        lcd_novo_char(1, stepB2);
        lcd_novo_char(2, stepB3);
        lcd_novo_char(3, stepB4);
        lcd_novo_char(4, stepB5);
        lcd_novo_char(5, stepB6);
        lcd_cursor_ddram(b, 1);
        lcd_putch(0);
        lcd_cursor_ddram(b, 0);
        lcd_putch(1);
        lcd_cursor_ddram(c, 1);
        lcd_putch(2);
        lcd_cursor_ddram(c, 0);
        lcd_putch(3);
        lcd_cursor_ddram(d, 1);
        lcd_putch(4);
        lcd_cursor_ddram(d, 0);
        lcd_putch(5);
        delay_ms(150);
        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepC1);
        lcd_novo_char(1, stepC2);
        lcd_novo_char(2, stepC3);
        lcd_novo_char(3, stepC4);
        lcd_novo_char(4, stepC5);
        lcd_novo_char(5, stepC6);
        lcd_cursor_ddram(c, 1);
        lcd_putch(0);
        lcd_cursor_ddram(c, 0);
        lcd_putch(1);
        lcd_cursor_ddram(d, 1);
        lcd_putch(2);
        lcd_cursor_ddram(d, 0);
        lcd_putch(3);
        lcd_cursor_ddram(e, 1);
        lcd_putch(4);
        lcd_cursor_ddram(e, 0);
        lcd_putch(5);
        delay_ms(150);
        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepB1);
        lcd_novo_char(1, stepB2);
        lcd_novo_char(2, stepB3);
        lcd_novo_char(3, stepB4);
        lcd_novo_char(4, stepB5);
        lcd_novo_char(5, stepB6);
        lcd_cursor_ddram(d, 1);
        lcd_putch(0);
        lcd_cursor_ddram(d, 0);
        lcd_putch(1);
        lcd_cursor_ddram(e, 1);
        lcd_putch(2);
        lcd_cursor_ddram(e, 0);
        lcd_putch(3);
        lcd_cursor_ddram(f, 1);
        lcd_putch(4);
        lcd_cursor_ddram(f, 0);
        lcd_putch(5);
        delay_ms(150);
        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepD1);
        lcd_novo_char(1, stepD2);
        lcd_novo_char(2, stepD3);
        lcd_novo_char(3, stepD4);
        lcd_novo_char(4, stepD5);
        lcd_novo_char(5, stepD6);
        lcd_cursor_ddram(e, 1);
        lcd_putch(0);
        lcd_cursor_ddram(e, 0);
        lcd_putch(1);
        lcd_cursor_ddram(f, 1);
        lcd_putch(2);
        lcd_cursor_ddram(f, 0);
        lcd_putch(3);
        lcd_cursor_ddram(g, 1);
        lcd_putch(4);
        lcd_cursor_ddram(g, 0);
        lcd_putch(5);
        delay_ms(150);
    }
}

void homem_vira_direita(void) {
    int a = 13;
    int b = a + 1;
    int c = a + 2;
    lcd_clear();
    lcd_string((char *) "----------------", LCD_LINHA3);
    lcd_novo_char(0, slipA1);
    lcd_novo_char(1, slipA2);
    lcd_novo_char(2, slipA3);
    lcd_novo_char(3, slipA4);
    lcd_novo_char(4, slipA5);
    lcd_novo_char(5, slipA6);
    lcd_cursor_ddram(a, 1);
    lcd_putch(0);
    lcd_cursor_ddram(a, 0);
    lcd_putch(1);
    lcd_cursor_ddram(b, 1);
    lcd_putch(2);
    lcd_cursor_ddram(b, 0);
    lcd_putch(3);
    lcd_cursor_ddram(c, 1);
    lcd_putch(4);
    lcd_cursor_ddram(c, 0);
    lcd_putch(5);
    delay_ms(150);
    lcd_clear();
    lcd_string((char *) "----------------", LCD_LINHA3);
    lcd_novo_char(0, slipB1);
    lcd_novo_char(1, slipB2);
    lcd_novo_char(2, slipB3);
    lcd_novo_char(3, slipB4);
    lcd_novo_char(4, slipB5);
    lcd_novo_char(5, slipB6);
    lcd_cursor_ddram(a, 1);
    lcd_putch(0);
    lcd_cursor_ddram(a, 0);
    lcd_putch(1);
    lcd_cursor_ddram(b, 1);
    lcd_putch(2);
    lcd_cursor_ddram(b, 0);
    lcd_putch(3);
    lcd_cursor_ddram(c, 1);
    lcd_putch(4);
    lcd_cursor_ddram(c, 0);
    lcd_putch(5);
    delay_ms(150);
    lcd_novo_char(0, slipC1);
    lcd_novo_char(1, slipC2);
    lcd_novo_char(2, slipC3);
    lcd_novo_char(3, slipC4);
    lcd_novo_char(4, slipC5);
    lcd_novo_char(5, slipC6);
    lcd_cursor_ddram(a, 1);
    lcd_putch(0);
    lcd_cursor_ddram(a, 0);
    lcd_putch(1);
    lcd_cursor_ddram(b, 1);
    lcd_putch(2);
    lcd_cursor_ddram(b, 0);
    lcd_putch(3);
    lcd_cursor_ddram(c, 1);
    lcd_putch(4);
    lcd_cursor_ddram(c, 0);
    lcd_putch(5);
    delay_ms(150);
}

void homem_corre_direita(void) {
    unsigned char a, b, c, d, e, f, g;

    for (a = 16; a > 4; a -= 4) {
        b = a - 1;
        c = a - 2;
        d = a - 3;
        e = a - 4;
        f = a - 5;
        g = a - 6;

        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepE1);
        lcd_novo_char(1, stepE2);
        lcd_novo_char(2, stepE3);
        lcd_novo_char(3, stepE4);
        lcd_novo_char(4, stepE5);
        lcd_novo_char(5, stepE6);
        lcd_cursor_ddram(d, 1);
        lcd_putch(0);
        lcd_cursor_ddram(d, 0);
        lcd_putch(1);
        lcd_cursor_ddram(c, 1);
        lcd_putch(2);
        lcd_cursor_ddram(c, 0);
        lcd_putch(3);
        lcd_cursor_ddram(b, 1);
        lcd_putch(4);
        lcd_cursor_ddram(b, 0);
        lcd_putch(5);
        delay_ms(150);
        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepF1);
        lcd_novo_char(1, stepF2);
        lcd_novo_char(2, stepF3);
        lcd_novo_char(3, stepF4);
        lcd_novo_char(4, stepF5);
        lcd_novo_char(5, stepF6);
        lcd_cursor_ddram(e, 1);
        lcd_putch(0);
        lcd_cursor_ddram(e, 0);
        lcd_putch(1);
        lcd_cursor_ddram(d, 1);
        lcd_putch(2);
        lcd_cursor_ddram(d, 0);
        lcd_putch(3);
        lcd_cursor_ddram(c, 1);
        lcd_putch(4);
        lcd_cursor_ddram(c, 0);
        lcd_putch(5);
        delay_ms(150);
        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepE1);
        lcd_novo_char(1, stepE2);
        lcd_novo_char(2, stepE3);
        lcd_novo_char(3, stepE4);
        lcd_novo_char(4, stepE5);
        lcd_novo_char(5, stepE6);
        lcd_cursor_ddram(f, 1);
        lcd_putch(0);
        lcd_cursor_ddram(f, 0);
        lcd_putch(1);
        lcd_cursor_ddram(e, 1);
        lcd_putch(2);
        lcd_cursor_ddram(e, 0);
        lcd_putch(3);
        lcd_cursor_ddram(d, 1);
        lcd_putch(4);
        lcd_cursor_ddram(d, 0);
        lcd_putch(5);
        delay_ms(150);
        lcd_clear();
        lcd_string((char *) "----------------", LCD_LINHA3);
        lcd_novo_char(0, stepG1);
        lcd_novo_char(1, stepG2);
        lcd_novo_char(2, stepG3);
        lcd_novo_char(3, stepG4);
        lcd_novo_char(4, stepG5);
        lcd_novo_char(5, stepG6);
        lcd_cursor_ddram(g, 1);
        lcd_putch(0);
        lcd_cursor_ddram(g, 0);
        lcd_putch(1);
        lcd_cursor_ddram(f, 1);
        lcd_putch(2);
        lcd_cursor_ddram(f, 0);
        lcd_putch(3);
        lcd_cursor_ddram(e, 1);
        lcd_putch(4);
        lcd_cursor_ddram(e, 0);
        lcd_putch(5);
        delay_ms(150);
    }
}

void homem_vira_esquerda(void) {
    int a, b, c;
    a = 1;
    b = a + 1;
    c = a + 2;
    lcd_clear();
    lcd_string((char *) "----------------", LCD_LINHA3);
    lcd_novo_char(0, slipD1);
    lcd_novo_char(1, slipD2);
    lcd_novo_char(2, slipD3);
    lcd_novo_char(3, slipD4);
    lcd_novo_char(4, slipD5);
    lcd_novo_char(5, slipD6);
    lcd_cursor_ddram(a, 1);
    lcd_putch(0);
    lcd_cursor_ddram(a, 0);
    lcd_putch(1);
    lcd_cursor_ddram(b, 1);
    lcd_putch(2);
    lcd_cursor_ddram(b, 0);
    lcd_putch(3);
    lcd_cursor_ddram(c, 1);
    lcd_putch(4);
    lcd_cursor_ddram(c, 0);
    lcd_putch(5);
    delay_ms(150);
    lcd_clear();
    lcd_string((char *) "----------------", LCD_LINHA3);
    lcd_novo_char(0, slipE1);
    lcd_novo_char(1, slipE2);
    lcd_novo_char(2, slipE3);
    lcd_novo_char(3, slipE4);
    lcd_novo_char(4, slipE5);
    lcd_novo_char(5, slipE6);
    lcd_cursor_ddram(a, 1);
    lcd_putch(0);
    lcd_cursor_ddram(a, 0);
    lcd_putch(1);
    lcd_cursor_ddram(b, 1);
    lcd_putch(2);
    lcd_cursor_ddram(b, 0);
    lcd_putch(3);
    lcd_cursor_ddram(c, 1);
    lcd_putch(4);
    lcd_cursor_ddram(c, 0);
    lcd_putch(5);
    delay_ms(150);
    lcd_novo_char(0, slipF1);
    lcd_novo_char(1, slipF2);
    lcd_novo_char(2, slipF3);
    lcd_novo_char(3, slipF4);
    lcd_novo_char(4, slipF5);
    lcd_novo_char(5, slipF6);
    lcd_cursor_ddram(a, 1);
    lcd_putch(0);
    lcd_cursor_ddram(a, 0);
    lcd_putch(1);
    lcd_cursor_ddram(b, 1);
    lcd_putch(2);
    lcd_cursor_ddram(b, 0);
    lcd_putch(3);
    lcd_cursor_ddram(c, 1);
    lcd_putch(4);
    lcd_cursor_ddram(c, 0);
    lcd_putch(5);
    delay_ms(150);
}

void homem_animacao(void) {
    lcd_clear();
    homem_inicio();
    homem_corre_esquerda();
    homem_vira_direita();
    homem_corre_direita();
    homem_vira_esquerda();
    lcd_string((char *) "FIM....", LCD_LINHA4);
}